// MZ-Lang Code Generator
// Produces assembly-like pseudo-code from the AST

class CodeGen {
  constructor() {
    this.instructions = [];
    this.labelCount = 0;
    this.tempCount = 0;
    this.dataSection = [];
    this.textSection = [];
  }

  newLabel(prefix = 'L') {
    return `${prefix}_${++this.labelCount}`;
  }

  newTemp() {
    return `t${++this.tempCount}`;
  }

  emit(op, args = '', comment = '') {
    this.textSection.push({ op, args, comment, isLabel: false });
  }

  emitLabel(label, comment = '') {
    this.textSection.push({ op: label + ':', args: '', comment, isLabel: true });
  }

  emitData(name, type, value) {
    this.dataSection.push({ name, type, value });
  }

  gen(node) {
    if (!node) return '';

    switch (node.type) {
      case 'Program':
        this.emit('; === MY-Lang Assembly Output ===');
        this.emit('; Generated by MY-Lang Compiler v1.0');
        this.emit('');
        this.emitLabel('_start', 'Program entry point');
        node.body.forEach(s => this.gen(s));
        this.emit('HALT', '', 'end of program');
        return '';

      case 'Block':
        node.body.forEach(s => this.gen(s));
        return '';

      case 'VarDecl': {
        const t = node.varType === 'number' ? 'NUM' : node.varType === 'text' ? 'STR' : 'BOOL';
        this.emitData(node.name, t, node.init ? '?' : '0');
        if (node.init) {
          const src = this.gen(node.init);
          this.emit('STORE', `[${node.name}], ${src}`, `declare ${node.varType} ${node.name}`);
        } else {
          this.emit('STORE', `[${node.name}], 0`, `declare ${node.varType} ${node.name} (default)`);
        }
        return `[${node.name}]`;
      }

      case 'ArrayDecl': {
        this.emitData(node.name, 'ARR', `[${node.elements.length}]`);
        node.elements.forEach((el, i) => {
          const val = this.gen(el);
          this.emit('STORE', `[${node.name}+${i}], ${val}`, `init ${node.name}[${i}]`);
        });
        return `[${node.name}]`;
      }

      case 'Assign': {
        const val = this.gen(node.value);
        this.emit('STORE', `[${node.name}], ${val}`, `assign ${node.name}`);
        return `[${node.name}]`;
      }

      case 'IndexAssign': {
        const idx = this.gen(node.index);
        const val = this.gen(node.value);
        const idxReg = this.newTemp();
        this.emit('LOAD', `${idxReg}, ${idx}`, 'load index');
        this.emit('STORE', `[${node.name}+${idxReg}], ${val}`, `assign ${node.name}[...]`);
        return '';
      }

      case 'IfStmt': {
        const cond = this.gen(node.condition);
        const elseLabel = this.newLabel('ELSE');
        const endLabel = this.newLabel('END_IF');
        this.emit('CMP', `${cond}, 0`, 'evaluate condition');
        this.emit('JEQ', elseLabel, 'jump to else if false');
        this.gen(node.consequent);
        this.emit('JMP', endLabel, 'skip else');
        this.emitLabel(elseLabel, 'else branch');
        if (node.alternate) this.gen(node.alternate);
        this.emitLabel(endLabel, 'end if');
        return '';
      }

      case 'WhileStmt': {
        const loopLabel = this.newLabel('LOOP');
        const exitLabel = this.newLabel('LOOP_EXIT');
        this.emitLabel(loopLabel, 'while loop start');
        const cond = this.gen(node.condition);
        this.emit('CMP', `${cond}, 0`, 'check loop condition');
        this.emit('JEQ', exitLabel, 'exit if false');
        this.gen(node.body);
        this.emit('JMP', loopLabel, 'repeat loop');
        this.emitLabel(exitLabel, 'while loop end');
        return '';
      }

      case 'PrintStmt': {
        node.args.forEach(arg => {
          const val = this.gen(arg);
          this.emit('PRINT', val, 'output');
        });
        return '';
      }

      case 'ExprStmt':
        return this.gen(node.expr);

      case 'BinaryExpr': {
        const left = this.gen(node.left);
        const right = this.gen(node.right);
        const dest = this.newTemp();
        const opMap = {
          '+': 'ADD', '-': 'SUB', '*': 'MUL', '/': 'DIV', '%': 'MOD',
          '>': 'CGT', '<': 'CLT', '>=': 'CGE', '<=': 'CLE',
          '==': 'CEQ', '!=': 'CNE', '&&': 'AND', '||': 'OR',
          'and': 'AND', 'or': 'OR',
        };
        const instr = opMap[node.op] || 'ADD';
        this.emit(instr, `${dest}, ${left}, ${right}`, `${node.op} operation`);
        return dest;
      }

      case 'UnaryExpr': {
        const operand = this.gen(node.operand);
        const dest = this.newTemp();
        if (node.op === '-') this.emit('NEG', `${dest}, ${operand}`, 'negate');
        else this.emit('NOT', `${dest}, ${operand}`, 'logical not');
        return dest;
      }

      case 'Literal':
        if (node.kind === 'string') return `"${node.value}"`;
        if (node.kind === 'boolean') return node.value ? '1' : '0';
        return String(node.value);

      case 'Identifier':
        return `[${node.name}]`;

      case 'IndexExpr': {
        const idx = this.gen(node.index);
        const dest = this.newTemp();
        this.emit('LOAD', `${dest}, [${node.name}+${idx}]`, `index access ${node.name}[...]`);
        return dest;
      }

      case 'FuncCall': {
        const argRegs = node.args.map(a => this.gen(a));
        const dest = this.newTemp();
        argRegs.forEach((r, i) => this.emit('PUSH', r, `arg ${i + 1}`));
        this.emit('CALL', node.name, `function call`);
        this.emit('LOAD', `${dest}, RETVAL`, 'get return value');
        return dest;
      }

      case 'ArrayLiteral': {
        const dest = this.newTemp();
        node.elements.forEach((el, i) => {
          const val = this.gen(el);
          this.emit('STORE', `[${dest}+${i}], ${val}`, `array element ${i}`);
        });
        return dest;
      }

      default:
        return '#undefined';
    }
  }

  getOutput() {
    const lines = [];
    if (this.dataSection.length > 0) {
      lines.push({ isSection: true, text: '.DATA' });
      this.dataSection.forEach(d => {
        lines.push({ isData: true, name: d.name, type: d.type, value: d.value });
      });
      lines.push({ isEmpty: true });
    }
    lines.push({ isSection: true, text: '.TEXT' });
    this.textSection.forEach(ins => {
      lines.push(ins);
    });
    return lines;
  }
}

export function codegen(ast) {
  const gen = new CodeGen();
  gen.gen(ast);
  return gen.getOutput();
}
